In [23]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error as mse, mean_absolute_error as mae,root_mean_squared_error as rmse

Load the dataset.

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/SagarChhabriya/data-science/refs/heads/main/datasets/TBD/salary_dataset.csv')
df

     Experience Years  Salary
0                 0.6   27868
1                 0.6   31381
2                 0.7   44204
3                 0.8   39551
4                 0.9   25984
..                ...     ...
195              14.6  158775
196              14.6  160741
197              14.6  170198
198              14.8  154396
199              14.8  173265

[200 rows x 2 columns]

Explore and understand the data + Perform necessary data cleaning/preprocessing.

In [4]:
df.isnull().sum()

Experience Years    0
Salary              0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

Select relevant features and target variable + Split the data into training and testing sets where applicable.

In [10]:
x= df['Experience Years']
y= df['Salary']

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [15]:
x_train = x_train.values.reshape(-1, 1)
x_test = x_test.values.reshape(-1, 1)

Train an appropriate Machine Learning model.

In [16]:
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)

Evaluate the model using suitable evaluation metrics.

In [24]:
r2_score(y_pred, y_test)

0.9821864088840995

In [25]:
mse(y_pred, y_test)

23745684.25481864

In [26]:
mae(y_pred, y_test)

4056.3438613897365

In [27]:
rmse(y_pred, y_test)

4872.95436617445

Model Serialization

In [28]:
import pickle
with open("model.pkl", "wb") as file:
    pickle.dump(lr, file)

In [29]:
with open("model.pkl", "rb") as file:
    model = pickle.load(file)

In [30]:
df.head()

   Experience Years  Salary
0               0.6   27868
1               0.6   31381
2               0.7   44204
3               0.8   39551
4               0.9   25984

In [31]:
model.predict([[0.6]])

array([31417.94418739])

In [6]:
import sklearn as sk
import streamlit as st
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)
print(st.__version__)
print(sk.__version__)

2.5.4
3.0.6
1.66.0
1.9.1